# YaST2: modules testsuite
#
# Description:
#   Main file for all tests
#
# Author:
#   Michal Svec <msvec@suse.cz>
#
# $Id: testsuite.exp 13187 2004-01-13 14:54:45Z msvec $

global CASE
# there must be a space before the closing brace!
if [catch {set pattern $CASE }] {
    # CASE undefined, do a glob
    set pattern "*"
}

set filenames [lsort [glob "$srcdir/tests/$pattern.ycp"]]

puts "\nChecking started\n"

foreach file $filenames {
  if {[testsuite-run $file] < 0} {
    return
  }
}

puts "\nChecking finished\n"
